development:
  adapter: sqlite3
  database: db/development.db
  pool: 20
  timeout: 50000

test:
  adapter: sqlite3
  database: db/development.db
  pool: 20
  timeout: 50000

production:
  adapter: postgrsql
  database: db/development.db
  pool: 20
  timeout: 50000
