development:
  adapter: postgresql
  database: db/development.db
  pool: 20
  timeout: 5000

test:
  adapter: postgresql
  database: db/development.db
  pool: 20
  timeout: 5000

production:
  adapter: postgresql
  database: db/development.db
  pool: 20
  timeout: 5000
